### ISSUE TITLE
Missing selected icon on tracking protection list

### ISSUE THREAD

**Issue by lychichem** [lychichem/simplewhite#2]
After yesterday's update, Nightly add a feature of changing tracking protection list, which will cause this theme missing selected icon on lists.

**Comment by johngraciliano** [comment]
The rules involved in this were moved from:
`   `browser/preferences/in-content/search.css
to
`   `browser/preferences/in-content/preferences.css
This is just a quick note (but not a quick finding), I have not finish working the details.

p.s.  I am getting rid of the blue in the check marks, radio buttons, and in text input boxes borders, and also the yellow from the help button.  I think it is best to use shades of gray to match the themes motif.  This is just my first step to change the preferences page to look more like the addons page.  I know some people would think this is a backwards move, yet this is not the default theme has its own character.  If you have strong opinion against that change, please voice it.
